# Generated by Django 3.2.25 on 2024-04-11 14:35

from django.db import migrations, models
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_object_id_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(upload_to=uuid_upload_path.storage.upload_to, verbose_name='attachment'),
        ),
    ]
