# Generated by Django 3.2.20 on 2023-10-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_mempool_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='merge_identical',
            field=models.BooleanField(default=False),
        ),
    ]
