# Generated by Django 3.2.20 on 2023-11-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_merge_identical'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, default='/static/avatar.jpg', max_length=160),
        ),
    ]
