# Generated by Django 3.2.20 on 2023-11-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_cleanup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_hashtags',
            field=models.BooleanField(default=True),
        ),
    ]
