# Generated by Django 3.2.20 on 2023-11-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20231126_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_fiatfinances',
            field=models.BooleanField(default=True),
        ),
    ]
