# Generated by Django 3.2.20 on 2024-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_profile_my_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='electrum_hostname',
            field=models.CharField(default='bitcoin.lu.ke', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='electrum_ports',
            field=models.CharField(default='s50002', max_length=6),
        ),
    ]
