# Generated by Django 3.2.20 on 2024-01-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20240107_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='electrum_hostname',
            field=models.CharField(blank=True, default='bitcoin.lu.ke', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='electrum_ports',
            field=models.CharField(blank=True, default='s50002', max_length=6),
        ),
    ]
