# Generated by Django 3.2.20 on 2024-02-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20240107_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_sentry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_treemap',
            field=models.BooleanField(default=True),
        ),
    ]
