# Generated by Django 3.2.24 on 2024-03-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_profile_update_utxo_on_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='electrum_hostname',
            field=models.CharField(blank=True, default='electrum.emzy.de', max_length=255),
        ),
    ]
