# Generated by Django 3.2.24 on 2024-03-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_alter_profile_electrum_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_chatwoot',
            field=models.BooleanField(default=False),
        ),
    ]
