# Generated by Django 3.2.24 on 2024-03-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_profile_use_chatwoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_welcome_popup',
            field=models.BooleanField(default=False),
        ),
    ]
