# Generated by Django 3.2.25 on 2024-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_profile_has_seen_welcome_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='use_sentry',
            field=models.BooleanField(default=True),
        ),
    ]
