# Generated by Django 3.2.25 on 2024-03-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20240329_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='electrum_ports_test',
            field=models.CharField(blank=True, default='s51002', max_length=6),
        ),
    ]
