# Generated by Django 3.2.25 on 2024-04-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_alter_profile_electrum_ports_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_attachments',
            field=models.BooleanField(default=True),
        ),
    ]
