# Generated by Django 3.2.25 on 2025-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_profile_use_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_fee',
            field=models.IntegerField(default=1),
        ),
    ]
