# Generated by Django 3.2.25 on 2025-12-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_profile_my_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_fee_rate_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
