# Generated by Django 3.2.25 on 2025-12-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_profile_my_fee_rate_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_fee',
            field=models.IntegerField(default=1, help_text='Fee used when broadcasting transactions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_fee_rate_threshold',
            field=models.IntegerField(default=1, help_text='Overwrite healthy fee'),
        ),
    ]
