# Generated by Django 3.2.25 on 2025-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_auto_20251206_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_fee_rate_threshold',
            field=models.IntegerField(default=1, help_text='Adjust fee health thresholds (percentage points). Default: 0 = no adjustment, +1 = more lenient, -1 = more strict'),
        ),
    ]
