# Generated by Django 3.2.20 on 2023-10-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprice',
            options={'ordering': ['-timestamp']},
        ),
    ]
