# Generated by Django 3.2.20 on 2023-11-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_historicalprice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ref_hash', models.CharField(blank=True, help_text='Reflects type + ref, where type is TX', max_length=64)),
                ('spent', models.BooleanField(default=None, null=True)),
                ('value', models.IntegerField()),
                ('network', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')],
                 default='mainnet', help_text='Choose the network for this labelbase.', max_length=10)),
            ],
        ),
    ]
