# Generated by Django 3.2.20 on 2023-11-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_outputstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputstat',
            name='confirmed_at_block_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outputstat',
            name='confirmed_at_block_time',
            field=models.IntegerField(default=0),
        ),
    ]
