# Generated by Django 3.2.24 on 2024-02-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20231121_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputstat',
            name='type_ref_hash',
            field=models.CharField(blank=True, help_text='Reflects type + ref, where type is Output', max_length=64),
        ),
    ]
