# Generated by Django 3.2.24 on 2024-03-07 20:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20240307_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputstat',
            name='last_error',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
