# Generated by Django 3.2.25 on 2024-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_outputstat_next_input_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputstat',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', help_text="Choose the network for this labelbase's label output.", max_length=10),
        ),
    ]
