# Generated by Django 3.2.25 on 2024-07-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_alter_outputstat_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputstat',
            name='next_input_attributes',
        ),
        migrations.AddField(
            model_name='outputstat',
            name='next_enc_input_attrs',
            field=models.TextField(default=None, null=True),
        ),
    ]
