# Generated by Django 3.2.17 on 2023-02-01 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labelbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('fingerprint', models.CharField(max_length=8)),
                ('about', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tx', 'tx'), ('addr', 'addr'), ('pubkey', 'pubkey'), ('input', 'input'), ('output', 'output'), ('xpub', 'xpub')], default='addr', max_length=16)),
                ('ref', models.CharField(blank=True, default='', max_length=160)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('labelbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labelbase.labelbase')),
            ],
        ),
    ]
