# Generated by Django 3.2.17 on 2023-02-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelbase',
            name='about',
            field=models.CharField(default='', max_length=200),
        ),
    ]
