# Generated by Django 3.2.17 on 2023-02-08 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labelbase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="data",
        ),
    ]
