# Generated by Django 3.2.17 on 2023-02-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelbase', '0002_alter_labelbase_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelbase',
            name='about',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='labelbase',
            name='fingerprint',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
