# Generated by Django 3.2.20 on 2023-10-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelbase', '0004_alter_label_spendable'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelbase',
            name='operation_mode',
            field=models.CharField(choices=[('combine', 'Combine Identical Labels'), ('duplicate', 'Create Duplicate Entries (Default)'), ('replace', 'Replace Previous Records')], default='duplicate', help_text='Choose the operation mode for handling labels with the same type and reference. The default mode is to create duplicate entries.', max_length=10),
        ),
    ]
