# Generated by Django 3.2.20 on 2023-10-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelbase', '0006_auto_20231016_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelbase',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', help_text='Choose the network for this labelbase.', max_length=10),
        ),
    ]
