# Generated by Django 3.2.20 on 2023-10-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelbase', '0008_alter_label_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelbase',
            name='operation_mode',
            field=models.CharField(choices=[('combine', 'Combine Identical Entries'), ('duplicate', 'Create Duplicate Entries (Default)'), ('replace', 'Replace Previous Entries'), ('skip', 'Skip Identical Entries')], default='duplicate', help_text="Choose the operation mode for handling entries with the same 'type' and 'ref'. The default mode is to create duplicate entries.", max_length=10),
        ),
    ]
