FROM nginx:latest

COPY nginx.conf /etc/nginx/


#RUN apt-get update && \
#    apt-get install -y gettext-base && \
#    rm -rf /var/lib/apt/lists/*

#CMD /bin/bash -c "envsubst '$DOMAIN_NAME' < nginx.conf.template > /etc/nginx/nginx.conf"
