# Generated by Django 3.2.24 on 2024-03-12 10:43

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labelbase', '0010_alter_label_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=160))),
                ('description', django_cryptography.fields.encrypt(models.TextField(blank=True, default=''))),
                ('labelbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labelbase.labelbase')),
            ],
        ),
    ]
