# Generated by Django 3.2.20 on 2023-08-12 21:44

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labelbase', '0002_remove_label_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='origin',
            field=django_cryptography.fields.encrypt(models.CharField(
                blank=True, default='', help_text="Optional key origin information referencing the wallet associated with the label. The origin property should only appear where type is 'tx'.", max_length=160)),
        ),
        migrations.AddField(
            model_name='label',
            name='spendable',
            field=django_cryptography.fields.encrypt(models.BooleanField(
                default=False, help_text="One of true or false, denoting if an output should be spendable by the wallet. The spendable property only where type is 'output'.", max_length=160)),
        ),
    ]
