# Generated by Django 3.2.20 on 2023-10-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelbase', '0005_labelbase_operation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='type_ref_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='labelbase',
            name='operation_mode',
            field=models.CharField(choices=[('combine', 'Combine Identical Entries'), ('duplicate', 'Create Duplicate Entries (Default)'), ('replace', 'Replace Previous Entries')],
                                   default='duplicate', help_text="Choose the operation mode for handling entries with the same 'type' and 'ref'. The default mode is to create duplicate entries.", max_length=10),
        ),
    ]
