# Generated by Django 3.2.20 on 2023-11-02 23:08

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labelbase', '0009_alter_labelbase_operation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=1000)),
        ),
    ]
