# Generated by Django 3.2.25 on 2025-11-22 08:00

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labelbase', '0011_alter_labelbase_operation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='fee',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Transaction fee in satoshis (stored as string)', max_length=32, null=True)),
        ),
        migrations.AddField(
            model_name='label',
            name='fmv',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Fair market value (JSON string)', null=True)),
        ),
        migrations.AddField(
            model_name='label',
            name='height',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Block height where transaction was confirmed', max_length=16, null=True)),
        ),
        migrations.AddField(
            model_name='label',
            name='heights',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Block heights for address activity (JSON array as string)', null=True)),
        ),
        migrations.AddField(
            model_name='label',
            name='keypath',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Key derivation path (e.g., /1/123)', max_length=256, null=True)),
        ),
        migrations.AddField(
            model_name='label',
            name='rate',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Exchange rate at transaction time (JSON string)', null=True)),
        ),
        migrations.AddField(
            model_name='label',
            name='time',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='ISO-8601 timestamp of the block', max_length=64, null=True)),
        ),
        migrations.AddField(
            model_name='label',
            name='value',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Transaction value in satoshis, signed (stored as string)', max_length=32, null=True)),
        ),
    ]
